name: Continuous integration

on: [pull_request, push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Get the Repository)
        uses: actions/checkout@v2

      - name: Setup (prepare workflow to use Node v16)
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Install (ci = clean install)
        run: npm ci

      - name: Code style (static test)
        run: npm run lint

      - name: UI E2E Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: true
